### ISSUE TITLE
Saving data not only using browser

### ISSUE THREAD

**Issue by SerTetora** [benhar-dev/tchmi-save-as#1]
Hello Ben,

thank you very much for the great tutorial! I have a question: is it possible to save data into a file using some "SaveFileDialog" not only in a browser but also in a desktop app?

**Comment by benhar-dev** [comment]
Hi @SerTetora,

Is it possible to give a small example of what you are looking to do, just to help me understand what you are looking for?

**Comment by SerTetora** [comment]
Sorry, it was some TwinCat HMI bug, that I could not save the Json using LiveView, only in the browser it worked fine. Now it is working!

**Comment by benhar-dev** [comment]
Great to hear it's working!
